joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: "$(arg prefix)gen3_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - $(arg prefix)joint_1
      - $(arg prefix)joint_2
      - $(arg prefix)joint_3
      - $(arg prefix)joint_4
      - $(arg prefix)joint_5
      - $(arg prefix)joint_6
      - $(arg prefix)joint_7
      
  - name: /$(arg gripper_ns)/control/$(arg device_name)_synergy_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - $(arg device_name)_synergy_joint
